### ISSUE TITLE
Figma wireframes

### ISSUE THREAD

**Issue by tuttiq** [tuttiq/remote-izakaya#3]
Make wireframes of the basic UX flow on Figma

**Comment by drewpterry** [comment]
Please check this Figma link with basic wireframes + page flow. Please let me know if you have any comments.

https://www.figma.com/file/Cb2JMjGDa1RKEVyHENkFYf/Remote-Izakaya?node-id=0%3A1

**Comment by tuttiq** [comment]
LGTM for now
